# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
language: haskell

ghc:
  - "7.6.3"
  - "7.8.4"
  - "7.10.3"
  - "8.0.2"
  - "8.2.2"
  - "8.4.4"
  - "8.6.5"
  - "8.8.3"
  - "8.10.1"

before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install libcwiid-dev libsdl1.2-dev

install:
  - travis_retry cabal install --enable-tests -fexamples --only-dependencies yampa/ yampa-test/

script:
  - if [ "${TRAVIS_HASKELL_VERSION}" == "8.4.4" ]; then cabal install -ftest-doc-coverage --run-tests -j1  yampa/ yampa-test/; else cabal install --enable-tests -fexamples -j1 yampa/ yampa-test/; fi

after_script:

branches:
    only:
          - master
          - /^develop.*$/
          - /^hotfix.*$/
          - /^release.*$/
